#!/usr/bin/env ruby

require 'aurum'
require 'colorize'
require 'logger'


if ARGV.length < 1
    puts "Usage:\n\t#{File.basename($0)} source_dir"
else
    logger = Logger.new(STDOUT)
    source_dir = ARGV[0]
    if Dir.exists?(source_dir)
      Aurum::Configuration.new(source_dir).process
      logger.info("Project successfully processed".blue)
    else
      logger.error("Project source directory does not exist.".red)
    end
end

